baseURL = ""
#title = "VELAK ↯⚡"
title = "VELAK"
languageCode = "en-us"
defaultContentLanguage = "en"

paginate = 1000
rssLimit = 100
enableRobotsTXT = true
enableGitInfo = true
disableHugoGeneratorInject = true


#[permalinks]
    #program = '/:year/:month/:day/'

#[imaging]
    #[imaging.exif]
        #disableDate = false
        #disableLatLong = false
        #excludeFields = ''
        #includeFields = ''

[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5

[taxonomies]
    tag = "tags"
    artist = "artists"
    #category = "categories"

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]
    section = ["HTML","RSS"]
    taxonomyTerm = ["HTML", "RSS"]
    taxonomy = ["HTML", "RSS"]

