baseURL = ""
#title = "VELAK ↯⚡"
#title = "V´EL:AK"
title = "velak"
languageCode = "en-us"
defaultContentLanguage = "en"

paginate = 1000
rssLimit = 100

buildFuture = true
disableHugoGeneratorInject = true
enableGitInfo = true
enableRobotsTXT = true

[build]
    writeStats = true

#[permalinks]
    #program = '/:year/:month/:day/'

[imaging]
    quality = 80
    #[imaging.exif]
        #disableDate = false
        #disableLatLong = false
        #excludeFields = ''
        #includeFields = ''

[outputs]
    home = ["HTML"]
    #page = ["HTML", "JSON"]
    section = ["HTML","RSS","JSON"]
    #taxonomyTerm = ["HTML", "RSS"]
    #taxonomy = ["HTML", "RSS"]

[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5

[taxonomies]
    category = "categories"
    tag = "tags"
    #artist = "artists"
    #location = "locations"
