baseURL = ""
#title = "VELAK ↯⚡"
title = "VELAK"
languageCode = "en-us"
defaultContentLanguage = "en"
description = "Verein für Elektro Akustik"
keywords =  ["velak","verein","akustik","musik","events"]
theme_color = "#000000"

paginate = 1000
rssLimit = 100
enableRobotsTXT = true
enableGitInfo = true
disableHugoGeneratorInject = true

[taxonomies]
    tag = "tags"
    #category = "categories"
    #artist = "artists"

#[permalinks]
    #program = '/:year/:month/:day/'

[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]
    section = ["HTML","RSS"]
    taxonomyTerm = ["HTML", "RSS"]
    taxonomy = ["HTML", "RSS"]

