baseURL = ""
title = "velak"
languageCode = "en-us"
defaultContentLanguage = "en"

paginate = 1000
rssLimit = 100
buildFuture = true
disableHugoGeneratorInject = true
enableGitInfo = true
enableRobotsTXT = true

[build]
    writeStats = true

[imaging]
    quality = 90
    #[imaging.exif]
        #disableDate = false
        #disableLatLong = false
        #excludeFields = ''
        #includeFields = ''

[outputs]
    home = ["HTML","JSON"]
    section = ["HTML","JSON"]
    page = ["HTML","JSON"]
    #taxonomyTerm = ["HTML", "RSS"]
    #taxonomy = ["HTML", "RSS"]

# [permalinks]
#     program = '/:section/:year/:month/:filename/'

[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5

[taxonomies]
    tag = "tags"
    # artist = "artists"

