baseURL = ""
#title = "VELAK ↯⚡"
#title = "V´EL:AK"
title = "VELAK"
languageCode = "en-us"
defaultContentLanguage = "en"

paginate = 1000
rssLimit = 100

disableHugoGeneratorInject = true
enableGitInfo = true
enableRobotsTXT = true

#[permalinks]
    #program = '/:year/:month/:day/'

#[imaging]
    #[imaging.exif]
        #disableDate = false
        #disableLatLong = false
        #excludeFields = ''
        #includeFields = ''

#[outputs]
    #home = ["HTML", "RSS"]
    #page = ["HTML"]
    #section = ["HTML","RSS"]
    #taxonomyTerm = ["HTML", "RSS"]
    #taxonomy = ["HTML", "RSS"]

[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5

[taxonomies]
    artist = "artists"
    tag = "tags"
    #category = "categories"
