baseURL = ""
#baseURL = 'http://velak.ftl/'
title = "velak"
defaultContentLanguage = "en"
languageCode = "en-us"

paginate = 1000
rssLimit = 1000
buildFuture = true
disableHugoGeneratorInject = true
enableGitInfo = true
enableRobotsTXT = true

[build]
  writeStats = true

[imaging]
  quality = 90

[minify]
  minifyOutput = false
  # keepComments = true
  # keepConditionalComments = true

[outputs]
  home = ["HTML"]
  page = ["HTML","JSON"]
  #section = ["HTML","JSON"]
  #taxonomy = ["HTML", "RSS"]
  #term = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.txt]
    mediaType = "text/plain"
# [permalinks]
#     program = '/:section/:year/:month/:filename/'

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[taxonomies]
  tag = "tags"
  # artist = "artists"
