baseURL: ""
title: "velak"
defaultContentLanguage: "en"
languageCode: "en-us"

paginate: 1000
rssLimit: 1000
buildFuture: true
disableHugoGeneratorInject: true
#enableGitInfo: true
enableRobotsTXT: true

build:
  writeStats: true

imaging:
  quality: 90

minify:
  minifyOutput: false
  keepComments: true
  keepConditionalComments: true

outputs:
  home: ["HTML"]
  page: ["HTML"]
  section: ["HTML"]

mediaTypes:
  application/xml:
    suffixes:
    - xspf

outputFormats:
  xspf:
    baseName: velak
    isPlainText: true
    mediaType: application/xml
  m3u:
    baseName: velak.m3u
    isPlainText: true

sitemap:
  changefreq: 'monthly'
  filename: 'sitemap.xml'
  priority: 0.5

taxonomies:
  tag: "tags"
