description = "Verein für Elektro Akustik"
keywords =  ["velak","verein","akustik","musik","events"]
theme_color = "#000000"

publisher = "velak"
email = "velak@klingt.org"
repository = "https://github.com/disktree/velak"

[developer]
    email="tong@disktree.net"
    web = "https://disktree.net"
