name = "VELAK"
description = "Verein für Elektro Akustische Musik"
keywords =  ["velak","verein","akustik","musik","events","party"]
publisher = "velak"
url = "https://velak.klingt.org"
email = "velak@klingt.org"
mailannounce = "velak-announce@klingt.org"
mailman = "https://klingt.org/cgi-bin/mailman"
theme_color = "#000000"
dev = true

[contact]
    email = "velak@klingt.org"
    web = "https://velak.klingt.org"

[github]
    org = "verein-fuer-elektro-akustik"
    repo = "velak.klingt.org"

[developer]
    name = "disktree"
    email = "admin@disktree.net"
    url = "https://disktree.net/"
