name: "Malfunzionato Music Group"
description: "Malfunzionato Music Group"
keywords:
    [
        "malfunzionatomusicgroup",
        "malfunzionatorecordsindependent",
        "malfunzionatorecords",
        "music",
        "events",
        "party",
        "hiphop",
        "rap",
    ]
publisher: "malfunzionatomusicgroup"
url: "https://malfunzionatomusicgroup.com"
email: "contact@malfunzionatomusicgroup.com"
mailannounce: "mmg@malfunzionatomusicgroup.com"
mailman: "https://klingt.org/cgi-bin/mailman"
theme_color: "#000000"
theme: "polivoks"
dev: true

contact:
    email: "contact@malfunzionatomusicgroup.com"
    web: "https://malfunzionatomusicgroup.com"

github:
    org: "malfunzionatomusicgroupwb"
    repo: "P0rc0D10"

# livestream:
#   host: "https://rrr.disktree.net:8443"
#   stream: "velak"

developer:
    name: "disktree"
    email: "admin@disktree.net"
    url: "https://disktree.net/"
