description = "Verein für Elektro Akustische Musik"
email = "velak@klingt.org"
publisher = "velak"
repository = "https://github.com/disktree/velak"
[author]
    email="tong@disktree.net"
    web = "https://disktree.net"
