name: build

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Site baseurl'
        #default: 'https://velak.klingt.org' # TODO
        default: 'https://verein-fuer-elektro-akustik.github.io/velak.klingt.org/'
        required: true

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Cache resources
        id: cache-resources
        uses: actions/cache@v3
        with:
          path: resources
          key: hugo-resources
      - name: Setup npm
        run: npm install
      - name: Build style
        run: npm run prod:style
      - name: Build site
        run: npm run prod:hugo -- --baseURL ${{ inputs.url }}
      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: velak.klingt.org
          path: public
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: public
          clean: true
          single-commit: true
  # deploy:
  #   needs: build
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
  #       with:
  #         artifact_name: velak.klingt.org
